name: qr_make_read
description: "QR Code make & read App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Config
  logger: ^1.1.0
  intl: ^0.19.0

  # Bloc
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1

  # Ui
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_slidable: ^3.1.1
  flutter_launcher_icons: ^0.13.1

  # QR
  pretty_qr_code: ^3.3.0
  qr_code_scanner: ^1.0.1

  # Info
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2
  ios_utsname_ext: ^2.2.0

  # DB
  sqflite: ^2.0.3
  sqfentity: ^2.1.2+7
  sqfentity_gen: ^2.3.0+4

  # Firebase
  firebase_crashlytics: ^3.4.9

  # Advertise
  google_mobile_ads: ^5.1.0

  # Share
  share_plus: ^9.0.0
  url_launcher: ^6.3.0

  # Path
  external_path: ^1.0.3
  path_provider: ^2.1.3

dependency_overrides:
  leak_tracker_flutter_testing: 3.0.3
  leak_tracker_testing: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  build_verify: ^3.1.0
flutter:
  uses-material-design: true