// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

// ignore_for_file: non_constant_identifier_names

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Qr_history.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// Qr_history TABLE
class TableQr_history extends SqfEntityTableBase {
  TableQr_history() {
    // declare properties of EntityTable
    tableName = 'qr_history';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('data', DbType.text),
      SqfEntityFieldBase('createDate', DbType.datetime,
          minValue: DateTime.parse('1900-01-01')),
      SqfEntityFieldBase('type', DbType.bool),
    ];
    super.init();
  }
  static SqfEntityTableBase? _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableQr_history();
  }
}
// END TABLES

// BEGIN SEQUENCES
// identity SEQUENCE
class SequenceIdentitySequence extends SqfEntitySequenceBase {
  SequenceIdentitySequence() {
    sequenceName = 'identity';
    maxValue =
        9007199254740991; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceIdentitySequence? _instance;
  static SequenceIdentitySequence get getInstance {
    return _instance = _instance ?? SequenceIdentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class QrPixelDB extends SqfEntityModelProvider {
  QrPixelDB() {
    databaseName = myDbModel.databaseName;
    password = myDbModel.password;
    dbVersion = myDbModel.dbVersion;
    preSaveAction = myDbModel.preSaveAction;
    logFunction = myDbModel.logFunction;
    databaseTables = [
      TableQr_history.getInstance,
    ];

    sequences = [
      SequenceIdentitySequence.getInstance,
    ];

    bundledDatabasePath = myDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
    databasePath = myDbModel.databasePath;
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Qr_history
class Qr_history extends TableBase {
  Qr_history({this.id, this.data, this.createDate, this.type}) {
    _setDefaultValues();
    softDeleteActivated = false;
  }
  Qr_history.withFields(this.data, this.createDate, this.type) {
    _setDefaultValues();
  }
  Qr_history.withId(this.id, this.data, this.createDate, this.type) {
    _setDefaultValues();
  }
  // fromMap v2.0
  Qr_history.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['data'] != null) {
      data = o['data'].toString();
    }
    if (o['createDate'] != null) {
      createDate = int.tryParse(o['createDate'].toString()) != null
          ? DateTime.fromMillisecondsSinceEpoch(
              int.tryParse(o['createDate'].toString())!)
          : DateTime.tryParse(o['createDate'].toString());
    }
    if (o['type'] != null) {
      type = o['type'].toString() == '1' || o['type'].toString() == 'true';
    }
  }
  // FIELDS (Qr_history)
  int? id;
  String? data;
  DateTime? createDate;
  bool? type;

  // end FIELDS (Qr_history)

  static const bool _softDeleteActivated = false;
  Qr_historyManager? __mnQr_history;

  Qr_historyManager get _mnQr_history {
    return __mnQr_history = __mnQr_history ?? Qr_historyManager();
  }

  // METHODS
  @override
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (data != null || !forView) {
      map['data'] = data;
    }
    if (createDate != null) {
      map['createDate'] = forJson
          ? createDate!.toString()
          : forQuery
              ? createDate!.millisecondsSinceEpoch
              : createDate;
    } else if (createDate != null || !forView) {
      map['createDate'] = null;
    }
    if (type != null) {
      map['type'] = forQuery ? (type! ? 1 : 0) : type;
    } else if (type != null || !forView) {
      map['type'] = null;
    }

    return map;
  }

  @override
  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    map['id'] = id;
    if (data != null || !forView) {
      map['data'] = data;
    }
    if (createDate != null) {
      map['createDate'] = forJson
          ? createDate!.toString()
          : forQuery
              ? createDate!.millisecondsSinceEpoch
              : createDate;
    } else if (createDate != null || !forView) {
      map['createDate'] = null;
    }
    if (type != null) {
      map['type'] = forQuery ? (type! ? 1 : 0) : type;
    } else if (type != null || !forView) {
      map['type'] = null;
    }

    return map;
  }

  /// This method returns Json String [Qr_history]
  @override
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [Qr_history]
  @override
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  @override
  List<dynamic> toArgs() {
    return [
      data,
      createDate != null ? createDate!.millisecondsSinceEpoch : null,
      type
    ];
  }

  @override
  List<dynamic> toArgsWithIds() {
    return [
      id,
      data,
      createDate != null ? createDate!.millisecondsSinceEpoch : null,
      type
    ];
  }

  static Future<List<Qr_history>?> fromWebUrl(Uri uri,
      {Map<String, String>? headers}) async {
    try {
      final response = await http.get(uri, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR Qr_history.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(Uri uri, {Map<String, String>? headers}) {
    return http.post(uri, headers: headers, body: toJson());
  }

  static Future<List<Qr_history>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Qr_history>[];
    try {
      objList = list
          .map((qr_history) =>
              Qr_history.fromMap(qr_history as Map<String, dynamic>))
          .toList();
    } catch (e) {
      debugPrint(
          'SQFENTITY ERROR Qr_history.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Qr_history>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields,
      bool setDefaultValues = true}) async {
    final List<Qr_history> objList = <Qr_history>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Qr_history.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Qr_history by ID if exist, otherwise returns null
  /// Primary Keys: int? id
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: getById(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>returns [Qr_history] if exist, otherwise returns null
  Future<Qr_history?> getById(int? id,
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    if (id == null) {
      return null;
    }
    Qr_history? obj;
    final data = await _mnQr_history.getById([id]);
    if (data.length != 0) {
      obj = Qr_history.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Qr_history) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> save({bool ignoreBatch = true}) async {
    if (id == null || id == 0) {
      id = await _mnQr_history.insert(this, ignoreBatch);
    } else {
      await _mnQr_history.update(this);
    }

    return id;
  }

  /// Saves the (Qr_history) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record
  /// ignoreBatch = true as a default. Set ignoreBatch to false if you run more than one save() operation those are between batchStart and batchCommit
  /// <returns>Returns id
  @override
  Future<int?> saveOrThrow({bool ignoreBatch = true}) async {
    if (id == null || id == 0) {
      id = await _mnQr_history.insertOrThrow(this, ignoreBatch);

      isInsert = true;
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnQr_history.updateOrThrow(this);
    }

    return id;
  }

  /// saveAs Qr_history. Returns a new Primary Key value of Qr_history

  /// <returns>Returns a new Primary Key value of Qr_history
  @override
  Future<int?> saveAs({bool ignoreBatch = true}) async {
    id = null;

    return save(ignoreBatch: ignoreBatch);
  }

  /// saveAll method saves the sent List<Qr_history> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<Qr_history> qr_histories,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    List<dynamic>? result = [];
    // If there is no open transaction, start one
    final isStartedBatch = await QrPixelDB().batchStart();
    for (final obj in qr_histories) {
      await obj.save(ignoreBatch: false);
    }
    if (!isStartedBatch) {
      result = await QrPixelDB().batchCommit(
          exclusive: exclusive,
          noResult: noResult,
          continueOnError: continueOnError);
      for (int i = 0; i < qr_histories.length; i++) {
        if (qr_histories[i].id == null) {
          qr_histories[i].id = result![i] as int;
        }
      }
    }
    return result!;
  }

  /// Updates if the record exists, otherwise adds a new row
  /// <returns>Returns id
  @override
  Future<int?> upsert({bool ignoreBatch = true}) async {
    try {
      final result = await _mnQr_history.rawInsert(
          'INSERT OR REPLACE INTO qr_history (id, data, createDate, type)  VALUES (?,?,?,?)',
          [
            id,
            data,
            createDate != null ? createDate!.millisecondsSinceEpoch : null,
            type
          ],
          ignoreBatch);
      if (result! > 0) {
        saveResult = BoolResult(
            success: true,
            successMessage: 'Qr_history id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Qr_history id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Qr_history Save failed. Error: ${e.toString()}');
      return null;
    }
  }

  /// inserts or replaces the sent List<<Qr_history>> as a bulk in one transaction.
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  /// Returns a BoolCommitResult
  @override
  Future<BoolCommitResult> upsertAll(List<Qr_history> qr_histories,
      {bool? exclusive, bool? noResult, bool? continueOnError}) async {
    final results = await _mnQr_history.rawInsertAll(
        'INSERT OR REPLACE INTO qr_history (id, data, createDate, type)  VALUES (?,?,?,?)',
        qr_histories,
        exclusive: exclusive,
        noResult: noResult,
        continueOnError: continueOnError);
    return results;
  }

  /// Deletes Qr_history

  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    debugPrint('SQFENTITIY: delete Qr_history invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnQr_history
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnQr_history.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  @override
  Future<BoolResult> recover([bool recoverChilds = true]) {
    // not implemented because:
    final msg =
        'set useSoftDeleting:true in the table definition of [Qr_history] to use this feature';
    throw UnimplementedError(msg);
  }

  @override
  Qr_historyFilterBuilder select(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return Qr_historyFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect;
  }

  @override
  Qr_historyFilterBuilder distinct(
      {List<String>? columnsToSelect, bool? getIsDeleted}) {
    return Qr_historyFilterBuilder(this, getIsDeleted)
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {}

  @override
  void rollbackPk() {
    if (isInsert == true) {
      id = null;
    }
  }

  // END METHODS
  // BEGIN CUSTOM CODE
  /*
      you can define customCode property of your SqfEntityTable constant. For example:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODE
}
// endregion qr_history

// region Qr_historyField
class Qr_historyField extends FilterBase {
  Qr_historyField(Qr_historyFilterBuilder qr_historyFB) : super(qr_historyFB);

  @override
  Qr_historyFilterBuilder equals(dynamic pValue) {
    return super.equals(pValue) as Qr_historyFilterBuilder;
  }

  @override
  Qr_historyFilterBuilder equalsOrNull(dynamic pValue) {
    return super.equalsOrNull(pValue) as Qr_historyFilterBuilder;
  }

  @override
  Qr_historyFilterBuilder isNull() {
    return super.isNull() as Qr_historyFilterBuilder;
  }

  @override
  Qr_historyFilterBuilder contains(dynamic pValue) {
    return super.contains(pValue) as Qr_historyFilterBuilder;
  }

  @override
  Qr_historyFilterBuilder startsWith(dynamic pValue) {
    return super.startsWith(pValue) as Qr_historyFilterBuilder;
  }

  @override
  Qr_historyFilterBuilder endsWith(dynamic pValue) {
    return super.endsWith(pValue) as Qr_historyFilterBuilder;
  }

  @override
  Qr_historyFilterBuilder between(dynamic pFirst, dynamic pLast) {
    return super.between(pFirst, pLast) as Qr_historyFilterBuilder;
  }

  @override
  Qr_historyFilterBuilder greaterThan(dynamic pValue) {
    return super.greaterThan(pValue) as Qr_historyFilterBuilder;
  }

  @override
  Qr_historyFilterBuilder lessThan(dynamic pValue) {
    return super.lessThan(pValue) as Qr_historyFilterBuilder;
  }

  @override
  Qr_historyFilterBuilder greaterThanOrEquals(dynamic pValue) {
    return super.greaterThanOrEquals(pValue) as Qr_historyFilterBuilder;
  }

  @override
  Qr_historyFilterBuilder lessThanOrEquals(dynamic pValue) {
    return super.lessThanOrEquals(pValue) as Qr_historyFilterBuilder;
  }

  @override
  Qr_historyFilterBuilder inValues(dynamic pValue) {
    return super.inValues(pValue) as Qr_historyFilterBuilder;
  }

  @override
  Qr_historyField get not {
    return super.not as Qr_historyField;
  }
}
// endregion Qr_historyField

// region Qr_historyFilterBuilder
class Qr_historyFilterBuilder extends ConjunctionBase {
  Qr_historyFilterBuilder(Qr_history obj, bool? getIsDeleted)
      : super(obj, getIsDeleted) {
    _mnQr_history = obj._mnQr_history;
    _softDeleteActivated = obj.softDeleteActivated;
  }

  bool _softDeleteActivated = false;
  Qr_historyManager? _mnQr_history;

  /// put the sql keyword 'AND'
  @override
  Qr_historyFilterBuilder get and {
    super.and;
    return this;
  }

  /// put the sql keyword 'OR'
  @override
  Qr_historyFilterBuilder get or {
    super.or;
    return this;
  }

  /// open parentheses
  @override
  Qr_historyFilterBuilder get startBlock {
    super.startBlock;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  @override
  Qr_historyFilterBuilder where(String? whereCriteria,
      {dynamic parameterValue}) {
    super.where(whereCriteria, parameterValue: parameterValue);
    return this;
  }

  /// page = page number,
  /// pagesize = row(s) per page
  @override
  Qr_historyFilterBuilder page(int page, int pagesize) {
    super.page(page, pagesize);
    return this;
  }

  /// int count = LIMIT
  @override
  Qr_historyFilterBuilder top(int count) {
    super.top(count);
    return this;
  }

  /// close parentheses
  @override
  Qr_historyFilterBuilder get endBlock {
    super.endBlock;
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  Qr_historyFilterBuilder orderBy(dynamic argFields) {
    super.orderBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  Qr_historyFilterBuilder orderByDesc(dynamic argFields) {
    super.orderByDesc(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='field1, field2'
  /// Example 2: argFields = ['field1', 'field2']
  @override
  Qr_historyFilterBuilder groupBy(dynamic argFields) {
    super.groupBy(argFields);
    return this;
  }

  /// argFields might be String or List<String>.
  /// Example 1: argFields='name, date'
  /// Example 2: argFields = ['name', 'date']
  @override
  Qr_historyFilterBuilder having(dynamic argFields) {
    super.having(argFields);
    return this;
  }

  Qr_historyField _setField(
      Qr_historyField? field, String colName, DbType dbtype) {
    return Qr_historyField(this)
      ..param = DbParameter(
          dbType: dbtype, columnName: colName, wStartBlock: openedBlock);
  }

  Qr_historyField? _id;
  Qr_historyField get id {
    return _id = _setField(_id, 'id', DbType.integer);
  }

  Qr_historyField? _data;
  Qr_historyField get data {
    return _data = _setField(_data, 'data', DbType.text);
  }

  Qr_historyField? _createDate;
  Qr_historyField get createDate {
    return _createDate = _setField(_createDate, 'createDate', DbType.datetime);
  }

  Qr_historyField? _type;
  Qr_historyField get type {
    return _type = _setField(_type, 'type', DbType.bool);
  }

  /// Deletes List<Qr_history> bulk by query
  ///
  /// <returns>BoolResult res.success= true (Deleted), false (Could not be deleted)
  @override
  Future<BoolResult> delete([bool hardDelete = false]) async {
    buildParameters();
    var r = BoolResult(success: false);

    if (_softDeleteActivated && !hardDelete) {
      r = await _mnQr_history!.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _mnQr_history!.delete(qparams);
    }
    return r;
  }

  /// using:
  /// update({'fieldName': Value})
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  @override
  Future<BoolResult> update(Map<String, dynamic> values) {
    buildParameters();
    if (qparams.limit! > 0 || qparams.offset! > 0) {
      qparams.whereString =
          'id IN (SELECT id from qr_history ${qparams.whereString!.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit! > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset! > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _mnQr_history!.updateBatch(qparams, values);
  }

  /// This method always returns [Qr_history] Obj if exist, otherwise returns null
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> Qr_history?
  @override
  Future<Qr_history?> toSingle(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    buildParameters(pSize: 1);
    final objFuture = _mnQr_history!.toList(qparams);
    final data = await objFuture;
    Qr_history? obj;
    if (data.isNotEmpty) {
      obj = Qr_history.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method always returns [Qr_history]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toSingle(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns> Qr_history?
  @override
  Future<Qr_history> toSingleOrDefault(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    return await toSingle(
            preload: preload,
            preloadFields: preloadFields,
            loadParents: loadParents,
            loadedFields: loadedFields) ??
        Qr_history();
  }

  /// This method returns int. [Qr_history]
  /// <returns>int
  @override
  Future<int> toCount([VoidCallback Function(int c)? qr_historyCount]) async {
    buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final qr_historiesFuture = await _mnQr_history!.toList(qparams);
    final int count = qr_historiesFuture[0]['CNT'] as int;
    if (qr_historyCount != null) {
      qr_historyCount(count);
    }
    return count;
  }

  /// This method returns List<Qr_history> [Qr_history]
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  /// ex: toList(preload:true) -> Loads all related objects
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  /// <returns>List<Qr_history>
  @override
  Future<List<Qr_history>> toList(
      {bool preload = false,
      List<String>? preloadFields,
      bool loadParents = false,
      List<String>? loadedFields}) async {
    final data = await toMapList();
    final List<Qr_history> qr_historiesData = await Qr_history.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return qr_historiesData;
  }

  /// This method returns Json String [Qr_history]
  @override
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [Qr_history]
  @override
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [Qr_history]
  /// <returns>List<dynamic>
  @override
  Future<List<dynamic>> toMapList() async {
    buildParameters();
    return await _mnQr_history!.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [Qr_history]
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  /// <returns>List<String>
  @override
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParams = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParams) {
      buildParameters();
    }
    _retVal['sql'] = 'SELECT `id` FROM qr_history WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  @override
  Future<List<int>> toListPrimaryKey([bool buildParams = true]) async {
    if (buildParams) {
      buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _mnQr_history!.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [Qr_history]
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  @override
  Future<List<dynamic>> toListObject() async {
    buildParameters();

    final objectFuture = _mnQr_history!.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  /// Sample usage: await Qr_history.select(columnsToSelect: ['columnName']).toListString()
  @override
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o)? listString]) async {
    buildParameters();

    final objectFuture = _mnQr_history!.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns![0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion Qr_historyFilterBuilder

// region Qr_historyFields
class Qr_historyFields {
  static TableField? _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField? _fData;
  static TableField get data {
    return _fData = _fData ?? SqlSyntax.setField(_fData, 'data', DbType.text);
  }

  static TableField? _fCreateDate;
  static TableField get createDate {
    return _fCreateDate = _fCreateDate ??
        SqlSyntax.setField(_fCreateDate, 'createDate', DbType.datetime);
  }

  static TableField? _fType;
  static TableField get type {
    return _fType = _fType ?? SqlSyntax.setField(_fType, 'type', DbType.bool);
  }
}
// endregion Qr_historyFields

//region Qr_historyManager
class Qr_historyManager extends SqfEntityProvider {
  Qr_historyManager()
      : super(QrPixelDB(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static const String _tableName = 'qr_history';
  static const List<String> _primaryKeyList = ['id'];
  static const String _whereStr = 'id=?';
}

//endregion Qr_historyManager
/// Region SEQUENCE IdentitySequence
class IdentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o)? nextval]) async {
    final val = await QrPixelDBSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o)? currentval]) async {
    final val = await QrPixelDBSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o)? currentval]) async {
    final val = await QrPixelDBSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false, reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE IdentitySequence

class QrPixelDBSequenceManager extends SqfEntityProvider {
  QrPixelDBSequenceManager() : super(QrPixelDB());
}
// END OF ENTITIES
